### ISSUE TITLE
Will this work with ThinkPad X1 Yoga?

### ISSUE THREAD

**Issue by Z-Shang** [kfechter/YogaModeSwitch#3]
Are the addresses model specified or will generally work for all Yoga devices?

**Comment by kfechter** [comment]
I only have a yoga 14, so I can't speak for the other models.

In theory, it should work with all yoga models, it's just a matter of whether or not each yoga model uses the same Embedded Controller value change when the mode switches. 

If the thinkpad yoga models all use the same EC value switch, then the code will work as is on any yoga machine without modifications. if they are different, then the code would have to be modified with the specific memory addresses of the value that changes.

**Comment by Z-Shang** [comment]
fair enough, I'll give it a try when I have time to do so

**Comment by kfechter** [comment]
ok. If it doesn't work, let me know and I can try to find a way to figure out the values for the other models.
